### ISSUE TITLE
Wiki unaccessable.

### ISSUE THREAD

**Issue by Sanduhr32** [ReplayMod/ReplayStudio#5]
Hello dear ReplayMod team,

currently trying to help a friend and giving him some instruction.
While tried to help him i noticed, that i can not acces the wiki.
It may contain a redirect, that my browser locks or is inexistend.

Regards, Sanduhr32

**Comment by Johni0702** [comment]
Which wiki are you talking about? I don't recall having any ReplayMod related wiki.

**Comment by Sanduhr32** [comment]
I am talking about the wiki of this repo that you linked in the readme twice.

**Comment by Johni0702** [comment]
Ah, right, I'm sorry to disappoint but that wiki has never been written. I once decided it'd be a good idea to document the command line usage which is why I put the links in the README but never actually got around to do it.

This lib could probably do with a complete rewrite anyway as we're only using very specific parts of it in the ReplayMod and everything else has all the while been slowly degrading and/or has never been properly tested in the first place.
Most parts of this lib were even written before pathing was a real thing, so any modifications to the replay can result in the paths being wrong (or non-existent). Same goes for most other non-packet data.

The append command missing is another one of those cases where I've never used it and as such never noticed that it's not even implemented (I've opened #6 in case anyone gets around to fixing it).

Out of interest: What do you use the command line version of this lib for?

**Comment by Sanduhr32** [comment]
I dont use it personally. I just got contacted by a friend and tried to help him so i would say concating 60h of different replays.
